### PR TITLE
The time calculation are all done in ui.js, also the displayed ETA would follow the timezone of the browser (computer)

### PR DESCRIPTION
**Pull request by winstonma**
It should avoid the timezone difference between ui.js and ETA.js, as described in https://github.com/miklcct/kmb-lwb-combined-headway-eta/issues/4

All time calculation would be done in one place

### CODE REVIEW

**Comment by miklcct** [comment]
I'm now rewriting the whole library into async / await and module based modern Javascript so I'm closing this.

**Comment by winstonma** [comment]
Yeah pushing all the time calculation onto ui.js would make the code looks a bit weird. However the backend timezone problem comes out when I place the ETA fetcher code onto a docker (UTC by default) and run the ui code on browser (different timezone). That's why the time manipulation part is moved to ui.js. As you are running everything on the browser it won't be a problem. 

Waiting the the async / await code.

**Comment by miklcct** [comment]
The library code is now in the kmb-v2 branch and you can take a look. The library code is mostly complete however I will going to rewrite the frontend code using web components later.

**Comment by winstonma** [comment]
Wow this is a total rewrite!!! In addition it would make the code import easier (my selfish thought)!!!

By the way would you consider splitting your code into two parts (fetcher and UI), create a separate project for the fetcher code and build npm packages for fetcher (e.g. [feedme](https://www.npmjs.com/package/feedme)).

Also, is it possible that the fetcher support Node 10?

**Comment by miklcct** [comment]
I have split the fetcher into a new npm package js-kmb-api , but I think it need node 13 to run (because I'm writing ES6 modules, the support is only added in node 13). I have no plan to add compatibility code into it.

**Comment by winstonma** [comment]
@miklcct Thanks. I wish you would accept the pull request (if needed).

The reason for supporting Node 10 because [MagicMirror² Installation & Usage tutotial](https://docs.magicmirror.builders/getting-started/installation.html) teaches users to install Node 10 and I couldn't force people to upgrade. I understand that supporting Node 10 would not be your priority. I will try to use your module on my project and hope you would accept my backward compatibility pull request in the future.

Also, would you consider releasing [npm packages](https://blog.toright.com/posts/4874/%E5%A6%82%E4%BD%95%E7%99%BC%E4%BD%88%E4%BD%A0%E7%9A%84%E3%80%8C%E5%8C%85%E3%80%8D%E5%88%B0-npm-repository.html) 😀?

**Comment by winstonma** [comment]
@miklcct I installed your package and I'd like to write down the procedures.

1. Installed [js-kmb-api package](https://www.npmjs.com/package/js-kmb-api) using `npm install js-kmb-api`

2. Clone [js-kmb-api repo](https://github.com/miklcct/js-kmb-api), modify the following line in `tsconfig.json`
```
//"module": "es2015"
"module": "commonjs"
```

And then run `npm install && npm run build`. Then overwrite the js of the npm package with the newly generated js file.

3. Comment out `localStorage` and `sessionStorage`

4. Replace `jquery` get with [got](https://www.npmjs.com/package/got)

Everything works.

I am not trying to complain your work at all (you didn't work for me, instead I took advantage from your module). I just want to share this to see if it is possible to make a module generic enough that can work on both frontend and backend.

Thanks for your work =)

**Comment by miklcct** [comment]
This is still a beta version as there are still missing tests and also since frontend specific code not refactored yet. I plan to release the final 2.0.0 after handling all these things.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by winstonma** [comment]
Please treat the previous message as a beta feedback. I personally have no urgency on pushing a new version (everything works). And please take your time on the v2 release.

May I know what's your plan on the v2 of [kmb-lwb-combined-headway-eta](https://github.com/miklcct/kmb-lwb-combined-headway-eta)? You would want to have a backend + frontend or having everything on frontend?

**Comment by winstonma** [comment]
Just my 2 cent.

In the current release of the API you are returning a object. I am not sure but would returning a promise (or multiple promises) would be a considerable alternative?

**Comment by miklcct** [comment]
Please continue the discussion about the API in the API repository

**Pull request closed without merging**
